【OSCP】在 SecretFlow 中实现经典联邦策略 SCAFFOLD
secretflow/secretflow pull request #1074
Opened 2023-12-11 02:20 UTC by UMR99

#991 
**Type of change**

- [ ] Add new papers (Please tell us why you think this paper is awesome!)
- [ ] Fix the category of an existing paper/papers (Please tell us the reasons)
- [ ] Add a new tool/primitive/application with a new markdown page (Thank you! Also, please tell us more about this awesome thing!)

**Description**

> Please include a summary of the change and the relevant motivation.

2023-12-11 02:21 UTC, UMR99 commented
I have read the CLA Document and I hereby sign the CLA

2023-12-11 08:42 UTC, zhangxingmeng commented on secretflow/ml/nn/fl/backend/torch/strategy/scaffold_1.py
> +alice, bob, charlie = sf.PYU('alice'), sf.PYU('bob'), sf.PYU('charlie')
这里看起来是想写测试代码。我们一般测试是要通过pytest单测来进行测试，可以参考一下其他的单测代码完成一下这部分的单测。这里的代码可以考虑整理成为一个tutorial，后续可以作为文档输出。介绍scaffold的原理以及如何使用

2023-12-18 06:39 UTC, zhangxingmeng commented
有空更新一下pr，增加下单测，修复一下ci没通过的问题

2023-12-26 07:54 UTC, zhangxingmeng requested changes
Please sync main branch from secretflow, then submit after resolve conflict,thanks

2023-12-26 08:09 UTC, closed without merging