在 SecretFlow 中实现经典联邦策略 SCAFFOLD
secretflow/secretflow pull request #1103
Opened 2023-12-26 08:50 UTC by UMR99

Fixed: #991 
# Preamble

For Pull Request initiator, please read the following steps carefully. 请合并请求的发起人仔细阅读下列步骤。

---

If you are creating a `Pull Request` about listed topic below, please go the the `Preview` tab and click the relative link:
如果您要创建一个有关下列内容的的合并请求，请切换到 `Preview` 面板并点击下方相关的链接:

* Select [Awesome-PETs](?expand=1&template=pull_request_template_pets.md) for files under docs/awesome-pets

---

Select a proper `Pull Request` template can accelarate the review process, thanks for your cooperation.
选择一个正确的`合并请求`模版可以加速审查流程，谢谢您的配合

If your `Pull Request` topic is not amoung the list above, please just delete all prepopulated template content.
如果您的`合并请求`内容不在上述的列表里，请删除提前填入的模版内容。

---

Thanks for your contribution to SecretFlow project
感谢您对于 SecretFlow 项目的贡献

2023-12-26 08:51 UTC, UMR99 commented
I have read the CLA Document and I hereby sign the CLA

2024-01-15 07:49 UTC, zhangxingmeng commented on secretflow/ml/nn/fl/backend/torch/strategy/scaffold.py
> +from secretflow.ml.nn.fl.backend.torch.fl_base import BaseTorchModel
第三方库和local import之间空一行

2024-01-15 07:49 UTC, zhangxingmeng commented on secretflow/ml/nn/fl/backend/torch/strategy/scaffold.py
> +        self, weights: np.ndarray, cur_steps: int, train_steps: int, **kwargs,
麻烦用black格式化一下

2024-01-15 07:50 UTC, zhangxingmeng commented on secretflow/ml/nn/fl/backend/torch/strategy/scaffold.py
> +        # 在自己的模型中定义c和cg，如1.py line35所示
把这里注释转成自解释的，让读者能直接看懂，no ref

2024-02-22 08:22 UTC, zhangxingmeng commented on tests/ml/nn/sl/test_scaffold_torch.py
> +class TestScaffold(unittest.TestCase):
单测，请参考已有的单测文件，使用pytest进行改写。

2024-02-23 03:47 UTC, zhangxingmeng commented on secretflow/ml/nn/fl/backend/torch/strategy/scaffold.py
> +        if self.model.c is None:
什么情况下self.model.c会是None？

2024-02-23 03:47 UTC, zhangxingmeng commented on secretflow/ml/nn/fl/backend/torch/strategy/scaffold.py
> +                it = (torch.Tensor(it) + self.model.c[i] - self.model.cg[i]).tolist()
这里改用`torch.tensor`吧

2024-02-23 05:17 UTC, UMR99 commented on secretflow/ml/nn/fl/backend/torch/strategy/scaffold.py
> +        if self.model.c is None:
这里就是防止c未初始化，确保c非none就可以了

2024-04-08 03:13 UTC, zhangxingmeng commented on examples/app/h_cv/scaffold/scaffold.ipynb
这个文件先删掉吧，后续改成算法描述文档，具体的用法可以放在单测里面

2024-04-08 03:13 UTC, zhangxingmeng commented on tests/ml/nn/sl/test_scaffold_torch.py
> +import unittest
单测请改成pytest

2024-04-08 09:02 UTC, zhangxingmeng commented on examples/app/h_cv/fedper/fedper.ipynb
这个可以删掉吗

2024-04-08 10:11 UTC, UMR99 commented on tests/ml/nn/sl/test_scaffold_torch.py
上传出错了抱歉

2024-04-08 10:30 UTC, UMR99 commented on secretflow/ml/nn/fl/backend/torch/strategy/scaffold.py
> +from typing import Tuple
这里isort以后是不变的

2024-04-08 10:30 UTC, UMR99 commented on secretflow/ml/nn/fl/backend/torch/strategy/scaffold.py
> +import copy
已经添加了

2024-04-09 06:56 UTC, zhangxingmeng approved these changes
LGTM

2024-04-09 06:58 UTC, zhangxingmeng requested changes

2024-04-09 06:58 UTC, zhangxingmeng commented on tests/ml/nn/fl/strategy/test_fed_per_torch.py
这个为啥删掉了？

2024-04-09 10:33 UTC, UMR99 commented on tests/ml/nn/fl/strategy/test_fed_per_torch.py
这个是之前本地文件存的太乱了，然后上传时失误了

2024-04-10 07:56 UTC, zhangxingmeng approved these changes
LGTM

2024-04-10 08:04 UTC, zhangxingmeng commented on secretflow/ml/nn/fl/backend/torch/strategy/scaffold.py
> +from typing import Tuple
这个我再来调整吧，看起来还是不太对

2024-04-10 08:10 UTC, merged