ARM适配 cicd test
secretflow/secretflow pull request #1230
Opened 2024-04-03 03:04 UTC by wangzul

**Type of change**

添加了arm 适配代码

**Description**

主要添加了setup打包配置

2024-04-03 07:32 UTC, anakinxc commented on docker/release/python.Dockerfile
> +RUN  ARCH=$(uname -m) && \
Use TARGETPLATFORM

2024-04-03 07:32 UTC, anakinxc commented on docker/release/build.sh
> +# 启用或切换到特定的 docker buildx 构建器（如果尚未创建，请先创建）
English comment plz

2024-04-03 07:32 UTC, anakinxc commented on .circleci/testpypi-config.yml
> -# Define a job to be invoked later in a workflow.
@ian-huu Do we still need this testpypi workflow?

2024-04-08 02:43 UTC, ian-huu commented on .circleci/testpypi-config.yml
> -# Define a job to be invoked later in a workflow.
应该不需要了，可以删了

2024-04-08 02:43 UTC, ian-huu commented on .circleci/release-config.yml
> +            command: |
缩进问题

2024-04-08 06:49 UTC, anakinxc commented on .circleci/release-config.yml
> +            command: |
indentation

2024-04-08 06:49 UTC, anakinxc commented on .circleci/release-config.yml
> +
lint whitespaces

2024-04-09 06:47 UTC, ian-huu commented on docker/release/python.Dockerfile
> +    rm -f /root/Miniconda3.sh
看一下 anolis-lite.Dockerfile 和 anolis.Dockerfile，里面的 secretflow/base-ci:latest 应该没有 arm 版本，应该可以改成 secretflow/release-ci 和 secretflow/release-ci-aarch64

2024-04-11 10:34 UTC, anakinxc requested changes

2024-04-11 10:34 UTC, anakinxc commented on setup.py
> +            plat_name = "manylinux2014_aarch64"
use manylinux_2_28

2024-04-11 10:42 UTC, anakinxc submitted a review, later dismissed

2024-04-12 07:35 UTC, ian-huu approved these changes
LGTM

2024-04-12 07:43 UTC, anakinxc approved these changes

2024-04-15 02:55 UTC, merged