add fed_pac strategy based on torch backend
secretflow/secretflow pull request #1276
Opened 2024-04-28 07:59 UTC by Dorothy21650

**Type of change**

- [ ] Add new papers (Please tell us why you think this paper is awesome!)
- [ ] Fix the category of an existing paper/papers (Please tell us the reasons)
- [ x] Add a new tool/primitive/application with a new markdown page (Thank you! Also, please tell us more about this awesome thing!)

**Description**

> Please include a summary of the change and the relevant motivation.

2024-04-28 08:01 UTC, Dorothy21650 commented
I have read the CLA Document and I hereby sign the CLA

2024-04-28 08:03 UTC, wyanbing commented
I have read the CLA Document and I hereby sign the CLA

2024-04-30 02:32 UTC, ian-huu commented on secretflow/ml/nn/core/torch/module.py
> +class CifarCNN(BaseModule):
模型定义到 application 里，不要放在这里

2024-05-06 12:20 UTC, zhaocaibei123 requested changes
加个单测，参考 tests/ml/nn/fl/test_fl_model_torch.py

2024-05-06 12:20 UTC, zhaocaibei123 commented on secretflow/ml/nn/fl/backend/torch/fl_base.py
> +class FedPACTorchModel(BaseTorchModel):
这个类可以合到 strategy/fed_pac.py FedPAC

2024-05-06 12:20 UTC, zhaocaibei123 commented on secretflow/ml/nn/fl/backend/torch/strategy/fed_pac.py
> +        optimizer = torch.optim.SGD(
optimizer loss 之类的可以写到 TorchModel 里吗

2024-05-06 12:20 UTC, zhaocaibei123 commented on secretflow/ml/nn/fl/backend/torch/strategy/fed_pac.py
> +        for ep in range(epoch_classifier):
每个 step 训练一个 epoch 吗

2024-05-06 12:20 UTC, zhaocaibei123 commented on secretflow/security/aggregation/fedpac_aggregator.py
> +class FedPACAggregator(Aggregator):
average sum 逻辑没变的话可以继承 PlainAggregator

2024-05-10 14:53 UTC, Dorothy21650 commented on secretflow/ml/nn/fl/backend/torch/fl_base.py
> +        return step_per_epoch
已经修改（删除掉了，用的flbase中原有的做法），之前是为了跟源码里面对齐（源码中有在local_training中进行local_test），迁移过来之后，这个逻辑也删除了。

2024-05-10 14:53 UTC, Dorothy21650 commented on secretflow/ml/nn/fl/backend/torch/fl_base.py
> +        # self.dataset_size = torch.tensor(len(self.train_set.dataset)).to(self.exe_device)
Done

2024-05-10 14:54 UTC, Dorothy21650 commented on secretflow/ml/nn/core/torch/module.py
> +    def feature2logit(self, x):
Done.

2024-05-10 14:54 UTC, Dorothy21650 commented on secretflow/ml/nn/core/torch/module.py
> +class CifarCNN(BaseModule):
Done.

2024-05-10 14:57 UTC, Dorothy21650 commented on secretflow/ml/nn/fl/backend/torch/fl_base.py
> +        self.last_model = deepcopy(self.model)
这里是照搬源码的，源码是在本地训练开始之前保存的模型的深度副本，可能是考虑到了回滚，但是源码中也没有明确使用 self.last_model，现在已经删除掉这行了。

2024-05-10 14:57 UTC, Dorothy21650 commented on secretflow/ml/nn/fl/backend/torch/fl_base.py
> +class FedPACTorchModel(BaseTorchModel):
Done.

2024-05-15 06:27 UTC, zhaocaibei123 commented on secretflow/ml/nn/fl/backend/torch/fl_base.py
> +            return self.model.get_weights_not_bn(return_numpy=True)
这里 return_numpy 为什么写死？

2024-11-28 09:54 UTC, Candicepan commented
续一下

2025-01-05 09:41 UTC, closed without merging