在 SecretFlow 中实现简单场景下两方拆分 DIN 算法 #1003
secretflow/secretflow pull request #1476
Opened 2024-09-10 14:39 UTC by llm806

# Preamble

For Pull Request initiator, please read the following steps carefully. 请合并请求的发起人仔细阅读下列步骤。

---

If you are creating a `Pull Request` about listed topic below, please go the the `Preview` tab and click the relative link:
如果您要创建一个有关下列内容的的合并请求，请切换到 `Preview` 面板并点击下方相关的链接:

* Select [Awesome-PETs](?expand=1&template=pull_request_template_pets.md) for files under docs/awesome-pets

---

Select a proper `Pull Request` template can accelarate the review process, thanks for your cooperation.
选择一个正确的`合并请求`模版可以加速审查流程，谢谢您的配合

If your `Pull Request` topic is not amoung the list above, please just delete all prepopulated template content.
如果您的`合并请求`内容不在上述的列表里，请删除提前填入的模版内容。

---

Thanks for your contribution to SecretFlow project
感谢您对于 SecretFlow 项目的贡献

2024-09-20 09:40 UTC, zhaocaibei123 commented on secretflow/ml/nn/applications/sl_din_torch.py
> +# Copyright 2023 Ant Group Co., Ltd.
2024

2024-09-20 09:40 UTC, zhaocaibei123 commented on secretflow/ml/nn/applications/din_test.py
> +# Copyright 2023 Ant Group Co., Ltd.
2024
单测放到 tests/ml/nn/sl/extra/applications 目录下，有重复的函数定义直接 import，例如 generate_data

2024-09-21 03:49 UTC, Listennnnn commented on secretflow/ml/nn/applications/din_test.py
> +# Copyright 2023 Ant Group Co., Ltd.
单侧已放到对应目录，重复定义是指与哪里重复了？

2024-09-26 09:41 UTC, zhaocaibei123 commented on secretflow/ml/nn/applications/sl_din_torch.py
> +# Copyright 2023 Ant Group Co., Ltd.
2024

2024-09-26 09:41 UTC, zhaocaibei123 commented on tests/ml/nn/sl/applications/test_sl_din_torch.py
> +# Copyright 2023 Ant Group Co., Ltd.
2024
放到这个目录 tests/ml/nn/sl/extra/applications

2024-09-27 14:31 UTC, Listennnnn commented on tests/ml/nn/sl/applications/test_sl_din_torch.py
> +# Copyright 2023 Ant Group Co., Ltd.
已放到对应目录

2024-10-30 11:50 UTC, zhaocaibei123 commented on tests/ml/nn/sl/extra/applications/test_sl_din_torch.py
> +def generate_data(fea_emb_input_size, dataset_download_dir, gen_data_path):
这个函数和 tests/ml/nn/sl/extra/applications/test_sl_bst_torch.py  generate_data 有什么区别，没区别的话直接 import

2024-10-30 11:50 UTC, zhaocaibei123 commented on secretflow/ml/nn/applications/sl_din_torch.py
> +# Copyright 2023 Ant Group Co., Ltd.
所有文件 2024

2024-11-01 12:44 UTC, Listennnnn commented on tests/ml/nn/sl/extra/applications/test_sl_din_torch.py
> +def generate_data(fea_emb_input_size, dataset_download_dir, gen_data_path):
有细小改动

2024-11-12 08:35 UTC, zhaocaibei123 commented on tests/ml/nn/sl/extra/applications/test_sl_din_torch.py
> +def generate_data(fea_emb_input_size, dataset_download_dir, gen_data_path):
什么细小改动，有大段重复代码还是建议 import

2024-11-26 09:19 UTC, zhaocaibei123 commented on tests/ml/nn/sl/extra/applications/test_sl_din_torch.py
> +def generate_data(fea_emb_input_size, dataset_download_dir, gen_data_path):
改一下这个函数定义，把 sep 拿到参数里，这里 import，避免大段重复代码
btw：github 页面可以直接改代码

2024-11-26 09:53 UTC, zhaocaibei123 reviewed
__init__.py 文件没用吧，删一下

2024-11-26 11:26 UTC, zhaocaibei123 approved these changes

2024-11-26 12:45 UTC, Candicepan reviewed
LGTM

2024-11-26 12:48 UTC, Candicepan approved these changes

2024-11-27 03:07 UTC, warriorpaw commented
@Listennnnn 请在你的开发分支上rebase下secretflow:main分支，目录结构和ut规则都发生过改变，目前pr中的目录结构和ut都是最新的。

2024-11-27 06:30 UTC, warriorpaw requested changes

2024-11-27 06:30 UTC, warriorpaw commented on secretflow/ml/nn/applications/sl_din_torch.py
> +from secretflow.ml.nn.core.torch import BaseModule
[UT挂了](https://app.circleci.com/pipelines/github/secretflow/secretflow/2022/workflows/1491c92d-71ea-4667-9942-74884992a668/jobs/14929?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary)，关注下流水线的执行结果，这个import路径不对

2024-11-27 08:00 UTC, Listennnnn commented
我改了导包路径，现在是什么原因呢

2024-11-28 06:24 UTC, merged