add SME attack algorithm
secretflow/secretflow pull request #1596
Opened 2024-11-21 12:33 UTC by skylineZSS

## 使用隐语实现SME攻击
1. 添加了SME攻击算法和测试代码
2. 在`secretflow_fl/ml/nn/fl/backend/torch/fl_base.py`的`BaseTorchModel`类中添加了apply()函数

@zhaocaibei123

2024-11-26 09:46 UTC, zhaocaibei123 commented on examples/security/h_gia/SME_attack/test_torch_gia_sme.py
> +
black format 一下

2024-11-26 09:46 UTC, zhaocaibei123 commented on examples/security/h_gia/SME_attack/test_torch_gia_sme.py
> +    device_list = [alice]
这个攻击是只有一个worker参与方吗

2024-11-26 09:46 UTC, zhaocaibei123 commented on examples/security/h_gia/SME_attack/gia_sme_torch.py
> +# Copyright 2023 Ant Group Co., Ltd.
2024

2024-11-26 09:46 UTC, zhaocaibei123 commented on examples/security/h_gia/SME_attack/gia_sme_torch.py
> +import numpy as np
isort 一下

2024-11-26 09:46 UTC, zhaocaibei123 commented on examples/security/h_gia/README.md
> +1. Test SME attack on MNIST dataset
补充说明算法原理+代码实现说明+实验效果

2024-11-26 09:46 UTC, zhaocaibei123 commented on examples/security/h_gia/SME_attack/gia_sme_torch.py
> +        attacker = SME(
这么做相当于攻击在 driver 进行，实际上应该是 attack 方攻击 victim，应该把攻击行为放到 attack 方
SME 需要指定 attack 和 victim 方，如果需要 victim 的数据，可以 to 到 attack 方

2024-11-26 09:46 UTC, zhaocaibei123 commented on examples/security/h_gia/SME_attack/gia_sme_torch.py
> +        attacker = SME(
参考 secretflow_fl/ml/nn/sl/attacks/lia_torch.py secretflow_fl/ml/nn/sl/attacks/fia_torch.py

2024-11-26 09:46 UTC, zhaocaibei123 commented on examples/security/h_gia/SME_attack/gia_sme_torch.py
> +        self.victim_model1 = copy.deepcopy(reveal(self._workers[self.victim_party].apply(get_victim_model)))
话说这个算法把 victim 的模型、数据都拿到了，还要需要攻击什么

2024-12-06 07:49 UTC, skylineZSS commented on examples/security/h_gia/SME_attack/test_torch_gia_sme.py
> +    device_list = [alice]
是的，这里设置了一个worker作为victim，attacker是中心服务器

2024-12-06 07:50 UTC, skylineZSS commented on examples/security/h_gia/README.md
> +1. Test SME attack on MNIST dataset
已补充

2024-12-06 07:51 UTC, skylineZSS commented on examples/security/h_gia/SME_attack/gia_sme_torch.py
> +        attacker = SME(
已将攻击算法放到attack_party端执行

2024-12-06 07:53 UTC, skylineZSS commented on examples/security/h_gia/SME_attack/gia_sme_torch.py
> +        self.victim_model1 = copy.deepcopy(reveal(self._workers[self.victim_party].apply(get_victim_model)))
攻击者是服务端，模型参数可以获得
这里victim的数据只是用来评估攻击效果的，计算重构的隐私数据和真实数据的psnr，不会直接用于攻击

2024-12-26 07:06 UTC, zhaocaibei123 reviewed
图片尽量压缩到几十k

2024-12-26 07:06 UTC, zhaocaibei123 commented on examples/security/h_gia/SME_attack/gia_sme_torch.py
> +        attacker = SME(
这个 attacker 能不能也放到 attack 方，直接写到 _gia_sme_attack 里面就不用从 driver 传过去了

2024-12-26 07:06 UTC, zhaocaibei123 commented on examples/security/h_gia/SME_attack/gia_sme_torch.py
> +        return
这个 return 可以不写

2025-02-07 01:51 UTC, skylineZSS commented
1

2025-03-07 06:25 UTC, zhaocaibei123 approved these changes

2025-03-07 07:25 UTC, rivertalk commented
/gemini review

2025-03-07 12:22 UTC, skylineZSS commented on examples/security/h_gia/SME_attack/gia_sme_torch.py
> +        return self.metrics
已解决。
`gia_sme_attack`函数中将攻击过程中每一轮迭代优化的数据都保存在了`res.json`文件中，修改后的`get_attack_metrics`函数会读取这个文件并赋值给`self.metrics`

2025-03-07 12:26 UTC, skylineZSS commented on examples/security/h_gia/SME_attack/gia_sme_torch.py
> +                    mean_std=((0.0,), (1.0,)),
已解决。
现在在`attack_config`中可以根据不同数据集设置`mean_std`的值， 在攻击函数中`mean_std`从`attack_config`中读取

2025-03-10 03:13 UTC, warriorpaw requested changes
ci挂了，请修下ci

2025-03-10 03:13 UTC, warriorpaw commented on examples/security/h_gia/SME_attack/gia_sme_torch.py
> +            self.metrics = data
异常时，data局部变量不存在

2025-03-10 04:55 UTC, skylineZSS commented on examples/security/h_gia/SME_attack/gia_sme_torch.py
> +            self.metrics = data
已解决

2025-03-10 11:45 UTC, warriorpaw approved these changes
LGTM

2025-03-10 11:46 UTC, warriorpaw approved these changes
LGTM

2025-03-14 12:29 UTC, skylineZSS commented
I have read the CLA Document and I hereby sign the CLA

2025-03-14 12:33 UTC, skylineZSS commented
recheck

2025-03-17 03:19 UTC, skylineZSS commented
I have read the CLA Document and I hereby sign the CLA

2025-03-17 03:21 UTC, skylineZSS commented
I have read the CLA Document and I hereby sign the CLA

2025-03-17 03:23 UTC, Candicepan commented
> I have read the CLA Document and I hereby sign the CLA

recheck

2025-03-18 06:35 UTC, merged