Add DIAGNOSIS GrIDPure Implementation
secretflow/secretflow pull request #1622
Opened 2024-12-11 05:11 UTC by qwkkkkk

**Description**

This PR adds the reproduction code and experimental workflows for two algorithms:

1. **DIAGNOSIS**: ["DIAGNOSIS: Detecting Unauthorized Data Usages in Text-to-image Diffusion Models"](https://openreview.net/pdf?id=f8S3aLm0Vp).

2. **GrIDPure**: ["Can Protective Perturbation Safeguard Personal Data from Being Exploited by Stable Diffusion?"](https://openaccess.thecvf.com/content/CVPR2024/papers/Zhao_Can_Protective_Perturbation_Safeguard_Personal_Data_from_Being_Exploited_by_CVPR_2024_paper.pdf).

2024-12-11 08:14 UTC, qwkkkkk commented
I have read the CLA Document and I hereby sign the CLA

2025-04-11 03:45 UTC, ChengAnda commented
LGTM for algorithm

2025-04-15 07:25 UTC, warriorpaw requested changes

2025-04-15 07:25 UTC, warriorpaw commented on examples/security/aigc/GrIDPure/advdm_data/celebahq-caption/0.png
Please use methods such as submodule to reference *_data files from original source instead of copying them .

2025-04-15 07:56 UTC, qwkkkkk commented on examples/security/aigc/GrIDPure/advdm_data/celebahq-caption/0.png
✅ Data has been moved into a submodule for better repository management.

2025-05-15 03:24 UTC, closed without merging