Add sneakyprompt and mma-diffusion algorithms（Jailbreak attack algorithm）
secretflow/secretflow pull request #1632
Opened 2024-12-12 09:28 UTC by zsh24454

**Description**

> 越狱攻击的sneakyprompt以及mma-diffusion algorithms的实现

2024-12-12 09:46 UTC, zsh24454 commented
I have read the CLA Document and I hereby sign the CLA

2025-04-11 03:33 UTC, ChengAnda commented
LGTM for algorithm

2025-04-15 07:24 UTC, warriorpaw requested changes

2025-04-15 07:24 UTC, warriorpaw commented on examples/security/aigc/sneakyprompt/data/nsfw_list.txt
Delete these data files and describe how to get them in the readme. Do not copy them here.

2025-05-15 03:22 UTC, closed without merging