add WSL to use secretflow in windows
secretflow/secretflow pull request #247
Opened 2023-01-04 06:40 UTC by Mingbo-Lee

add how to install secretflow on windows by WSL so that a windows user can try or use  secretflow.

2023-01-04 06:44 UTC, Mingbo-Lee commented
I have read the CLA Document and I hereby sign the CLA

2023-01-04 07:24 UTC, zhouaihui requested changes

2023-01-04 07:24 UTC, zhouaihui commented on INSTALLATION.md
> +1. install WSL2 on Windows
`install` -> `Install`

2023-01-04 07:24 UTC, zhouaihui commented on INSTALLATION.md
> +- you are supposed to follow the [guide_zh](https://learn.microsoft.com/zh-cn/windows/wsl/install)  or [guide_en](https://learn.microsoft.com/en-us/windows/wsl/install)  to install WSL(Windows Subsys
`you` -> `You`

2023-01-04 07:24 UTC, zhouaihui commented on INSTALLATION.md
> +- you are supposed to follow the [guide_zh](https://learn.microsoft.com/zh-cn/windows/wsl/install)  or [guide_en](https://learn.microsoft.com/en-us/windows/wsl/install)  to install WSL(Windows Subsys
`Linux)  on your windows` -> `Linux) on your windows`, extra blank space

2023-01-04 07:24 UTC, zhouaihui commented on INSTALLATION.md
> +1. install WSL2 on Windows
Capitalize the first letter, thks. Same below

2023-01-06 07:10 UTC, zhouaihui commented
hi, @Mingbo-Lee , thanks for this improvement.
LGTM, just left some extra  blank space, could you check it again?

2023-01-07 02:06 UTC, Mingbo-Lee commented
Hello! @zhouaihui, Thank you very much for your advice. I have checked the spaces word by word and fixed some syntax errors. Would you please review my PR again?

2023-01-09 10:50 UTC, zhouaihui approved these changes
LGTM

2023-01-09 10:50 UTC, merged