[docs] add FedDataFrameDataLoader in english
secretflow/secretflow pull request #716
Opened 2023-07-09 07:28 UTC by hacker-jerry

**Description**

Add FedDataFrameDataLoader in english.

<img width="1260" alt="image" src="https://github.com/secretflow/secretflow/assets/57279550/60f785a4-8723-42c4-a83f-5d0a73501266">

<img width="718" alt="image" src="https://github.com/secretflow/secretflow/assets/57279550/d0a650b1-42f9-45fa-98d1-78e733857256">

2023-07-18 08:13 UTC, zhangxingmeng approved these changes
LGTM

2023-07-18 08:20 UTC, zhangxingmeng requested changes
You also need to add a PO file to provide the Chinese version.

2023-07-18 14:10 UTC, Mingbo-Lee reviewed
``"POT-Creation-Date: 2023-07-03 17:24+0800\n"``
Please generate the po file by yourself to get the newest version of your English translation.

2023-07-19 14:40 UTC, Mingbo-Lee commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/FedDataFrameDataLoader.po
> +
all these need to be removed.
ref to https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#documentation-update-and-its-multilingual-version

2023-07-20 01:30 UTC, Mingbo-Lee reviewed
LGTM

2023-07-20 01:31 UTC, Mingbo-Lee commented
Hi, @hacker-jerry ,  please upload the screenshot of Chinese version.

2023-07-20 01:40 UTC, Mingbo-Lee commented
> > Hi, @hacker-jerry , please upload the screenshot of Chinese version.
> 
> I've already upload the screenshot of Chinese version, please check it, thanks!

Sorry, Thank you for your work.
LGTM

2023-07-20 02:47 UTC, zhangxingmeng commented
可以给一下完整的页面截图吗？notebook不太好做reveal，需要确认渲染出来的结果是正确的

2023-07-20 03:10 UTC, zhangxingmeng commented
LGTM

2023-07-20 03:11 UTC, zhangxingmeng approved these changes

2023-07-20 03:11 UTC, merged