docs:Translate the CustomDataLoaderTorch.ipynb into English.
secretflow/secretflow pull request #731
Opened 2023-07-17 13:47 UTC by Zhang-gong

I translate the CustomDataLoaderTorch.ipynb into English.
I claimed this task in [issue#701](https://github.com/secretflow/secretflow/issues/701).

![image](https://github.com/secretflow/secretflow/assets/74176806/11392957-6a1c-41a1-88d1-7860b5284059)
![image](https://github.com/secretflow/secretflow/assets/74176806/226518f6-9214-4e77-9ae0-24d6e6a87687)
![image](https://github.com/secretflow/secretflow/assets/74176806/d566d7f7-f70a-4e98-a95a-7e84eac0f5db)
![image](https://github.com/secretflow/secretflow/assets/74176806/26bcd3ef-50ef-4777-afc0-abf7b3cb095c)
![image](https://github.com/secretflow/secretflow/assets/74176806/56386b67-0420-4fb0-9f01-bda66c9765b3)
![image](https://github.com/secretflow/secretflow/assets/74176806/4cdd473a-e50d-47b6-81ae-543d6fc9f911)

2023-07-17 13:49 UTC, Zhang-gong commented
I have read the CLA Document and I hereby sign the CLA

2023-07-18 07:59 UTC, zhangxingmeng commented
![image](https://github.com/secretflow/secretflow/assets/103552200/67d291a0-cc8c-49d5-a0b2-25a8b364f988)
emm, It seems like render is not right. order list should be one piece one line

2023-07-18 13:47 UTC, Mingbo-Lee commented on docs/tutorial/CustomDataLoaderTorch.ipynb
> +    "In FLModel, the usage of DataBuilder requires predefining a databuilder dictionary. It needs to be able to return `tf.dataset` and `steps_per_epoch`. Moreover, the `steps_per_epoch` returned by
`. It`->`, which`

2023-07-18 13:47 UTC, Mingbo-Lee commented on docs/tutorial/CustomDataLoaderTorch.ipynb
>     ]
`standalone`->`single-machine`

2023-07-18 14:06 UTC, Mingbo-Lee commented on docs/tutorial/CustomDataLoaderTorch.ipynb
> +    "In FLModel, the usage of DataBuilder requires predefining a databuilder dictionary. It needs to be able to return `tf.dataset` and `steps_per_epoch`. Moreover, the `steps_per_epoch` returned by
the usage of DataBuilder -> using DataBuilder

2023-07-20 07:23 UTC, Zhang-gong commented
I have solved the line feed problem, as well as the translation specification problem mentioned
![ee7978da559a2fcb348db9b40165343](https://github.com/secretflow/secretflow/assets/74176806/e5d94b08-c33d-40bf-aafb-31433c922d0f)

2023-07-20 07:26 UTC, Mingbo-Lee commented
LGTM.
Please commit the po file of the version of Chinese.

2023-07-20 08:00 UTC, Zhang-gong commented
update  'CustomDataLoaderTorch.po'
![6430849cb90528a174d17ffa6ed4c42](https://github.com/secretflow/secretflow/assets/74176806/44af3a45-bbf3-4448-b52e-d1f4f6ea8d5d)
![676a677894be8d49712aeb372263557](https://github.com/secretflow/secretflow/assets/74176806/29b0cc6d-b2c0-4b32-9cae-31de824ec456)
![Uploading 9f18ba1b2b4df1c24a87716e3390fb5.png…]()
![b94e8076d37638f6ad0030bec3e7648](https://github.com/secretflow/secretflow/assets/74176806/ff2e37c3-d728-4a29-9b55-c55f84b97a0c)
![6b814400c02f6f4c580d797cd91a88d](https://github.com/secretflow/secretflow/assets/74176806/6a670797-6d40-496b-8223-e3ce6c015c13)

2023-07-20 08:05 UTC, zhangxingmeng commented
![image](https://github.com/secretflow/secretflow/assets/103552200/ad6c3261-fad2-4fe0-a727-22190ee7ffd5)
这边怎么重复了

2023-07-20 08:06 UTC, zhangxingmeng commented
![image](https://github.com/secretflow/secretflow/assets/103552200/fe30e0f5-7db2-452c-97c6-9ed993f6db5a)
这里转义有点问题

2023-07-20 08:34 UTC, zhangxingmeng requested changes

2023-07-20 08:34 UTC, zhangxingmeng commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/CustomDataLoaderTorch.po
>  #~ msgid ""
#~开头的都删掉吧

2023-07-20 08:34 UTC, Zhang-gong commented on docs/locales/zh_CN/LC_MESSAGES/tutorial/CustomDataLoaderTorch.po
>  #~ msgid ""
OK

2023-07-20 08:39 UTC, Zhang-gong commented
修复了重复的提示。
![d29b08292d53e7cf44801aa6effc65b](https://github.com/secretflow/secretflow/assets/74176806/ef8a00e7-189a-4c58-9cc5-87485e6bc7a6)
修复了转义的错误。错误的原因是在中文部分`xxx`前后应当预留空格，否则不能正常渲染markdown语法。
![44f1e25d9f8fed2453b0c5bb5306fdc](https://github.com/secretflow/secretflow/assets/74176806/ae16d4f2-a9f0-4c79-a25c-ee65da33a207)

![66390ebf5115e461ffb91cb03fca005](https://github.com/secretflow/secretflow/assets/74176806/a6b5fe67-5a52-4e19-8fee-e56c70e6b085)
![bd19bf6ad0f261c0678185fab51cdba](https://github.com/secretflow/secretflow/assets/74176806/7cf1c266-3577-4f9e-9651-fff8e8cc5530)
![97ba3903c7d8c5926188ecee692d7d2](https://github.com/secretflow/secretflow/assets/74176806/07152124-f5d2-4bd0-a660-979be251c659)
![21342ae8c8112937f76afb64859d9f0](https://github.com/secretflow/secretflow/assets/74176806/d0f5a620-bbd2-49e5-a136-f3f2822edaaa)

2023-07-20 11:11 UTC, zhangxingmeng approved these changes
LGTM

2023-07-20 11:11 UTC, zhangxingmeng requested changes

2023-07-20 11:11 UTC, zhangxingmeng commented on docs/tutorial/CustomDataLoaderTorch.ipynb
> +    "# Next, we define a FLModel with a Torch backend for training."
这里的#去掉

2023-07-21 01:38 UTC, zhangxingmeng approved these changes
LGTM

2023-07-21 01:38 UTC, merged