add new PSI paper
secretflow/secretflow pull request #827
Opened 2023-08-17 02:09 UTC by xiansongq

**Type of change**

- [X] Add new papers (Please tell us why you think this paper is awesome!)
- [ ] Fix the category of an existing paper/papers (Please tell us the reasons)
- [ ] Add a new tool/primitive/application with a new markdown page (Thank you! Also, please tell us more about this awesome thing!)

**Description**

> Please include a summary of the change and the relevant motivation.
通常我们认为使用同态加密构造隐私集合求交协议似乎是一个疯狂的想法，但是在一些特定的应用场景如非平衡隐私集合求交，带标签的隐私集合求交，利用同态加密技术来构造是很有效的。本文结合特定的优化技术（布谷鸟哈希、分窗、划分、模转换）可以让同态加密隐私集合求交协议的性能在当时优于OT隐私集合求交协议。另外，本文介绍了很多有关多项式求值的方法，这也侧面影响了后面隐私集合求交协议的构造。

2023-08-17 02:10 UTC, xiansongq commented
I have read the CLA Document and I hereby sign the CLA

2023-09-05 01:15 UTC, Jamie-Cui requested changes

2023-09-05 01:15 UTC, Jamie-Cui commented on docs/awesome-pets/papers/applications/set/psi.md
> +- Fast Private Set Intersection from Homomorphic Encryption
可以尾部加两个空格吗？会渲染更好看一些 Thx

2023-09-05 01:15 UTC, Jamie-Cui commented on docs/awesome-pets/papers/applications/set/psi.md
> +  *Hao Chen, Kim Laine, Peter Rindal*
ditto

2023-09-12 09:59 UTC, Jamie-Cui commented
Hello 可以处理一下冲突吗，谢谢～ 后面我们会统一修改一下格式，可以忽略之前 comments 里面的格式要求，thanks

2023-09-15 02:44 UTC, Jamie-Cui approved these changes
LGTM

2023-09-15 02:44 UTC, merged