add new paper
secretflow/secretflow pull request #841
Opened 2023-08-24 03:20 UTC by ElioChan

**Type of change**

- [x] Add new papers (Please tell us why you think this paper is awesome!)
- [ ] Fix the category of an existing paper/papers (Please tell us the reasons)
- [ ] Add a new tool/primitive/application with a new markdown page (Thank you! Also, please tell us more about this awesome thing!)

**Description**

> Please include a summary of the change and the relevant motivation.

Add a new paper：Structure-Aware Private Set Intersection with Applications to Fuzzy matching.
It introduce new generic paradigm for structrue-aware Psi based on function secret-sharing(FSS) which improve the performance when one of the party's data strucutre is public known.  And  it develop several improved FSS techniques and explore Sa-PSI in depth a natural application of it, such as Fuzzy matching.

2023-08-24 03:22 UTC, ElioChan commented
I have read the CLA Document and I hereby sign the CLA

2023-09-05 01:14 UTC, Jamie-Cui requested changes

2023-09-05 01:14 UTC, Jamie-Cui commented on docs/awesome-pets/papers/applications/set/psi.md
> +- Structure-Aware Private Set Intersection with Applications to Fuzzy Matching
尾部可以加两个空格吗？会渲染的更好看一些

2023-09-05 01:14 UTC, Jamie-Cui commented on docs/awesome-pets/papers/applications/set/psi.md
> +- Malicious Secure, Structure-Aware Private Set Intersection
ditto

2023-09-05 01:14 UTC, Jamie-Cui commented on docs/awesome-pets/papers/applications/set/psi.md
> +  *Gayathri Garimella, Mike Rosulek, Jaspal Singh*
ditto

2023-09-05 13:27 UTC, ElioChan commented on docs/awesome-pets/papers/applications/set/psi.md
> +- Structure-Aware Private Set Intersection with Applications to Fuzzy Matching
好的

2023-09-05 14:04 UTC, Jamie-Cui approved these changes
LGTM

2023-09-12 09:55 UTC, merged