PSI paper
secretflow/secretflow pull request #865
Opened 2023-09-05 13:56 UTC by freepengui

**Type of change**

- [x] Add new papers (Please tell us why you think this paper is awesome!)
- [ ] Fix the category of an existing paper/papers (Please tell us the reasons)
- [ ] Add a new tool/primitive/application with a new markdown page (Thank you! Also, please tell us more about this awesome thing!)

**Description**

> Please include a summary of the change and the relevant motivation.
   文章提出了一个新的 PSI 协议，其底层是一个新的并且高效的可供双方对各自输入进行秘密比较的协议。本文提出的 PSI 协议分为线上和线下两个阶段，通过将非常昂贵的密码学操作放在线下阶段进行，其线上阶段对每一个元素仅需要4个快速的域操作，从而使得其线上阶段的运行非常高效

2023-09-05 14:03 UTC, Jamie-Cui requested changes
LGTM

2023-09-05 14:03 UTC, Jamie-Cui commented on docs/awesome-pets/papers/applications/set/psi.md
> +  Florian Kerschbaum, Erik-Oliver Blass, Rasoul Akhavan Mahdavi
Same for this line

2023-09-06 04:58 UTC, freepengui commented on docs/awesome-pets/papers/applications/set/psi.md
> +  Florian Kerschbaum, Erik-Oliver Blass, Rasoul Akhavan Mahdavi
is this OK?

2023-09-06 09:08 UTC, Jamie-Cui approved these changes
LGTM

2023-09-06 09:08 UTC, merged