【OSCP】拆分学习标签推理攻击算法 Norm Attack 和 Exploit Attack 算法实现
secretflow/secretflow pull request #871
Opened 2023-09-06 23:07 UTC by Zhangky11

Added implementation of the following label leakage attacks:
- ExPloit Attack
- Norm Attack

# Preamble

For Pull Request initiator, please read the following steps carefully. 请合并请求的发起人仔细阅读下列步骤。

---

If you are creating a `Pull Request` about listed topic below, please go the the `Preview` tab and click the relative link:
如果您要创建一个有关下列内容的的合并请求，请切换到 `Preview` 面板并点击下方相关的链接:

* Select [Awesome-PETs](?expand=1&template=pull_request_template_pets.md) for files under docs/awesome-pets

---

Select a proper `Pull Request` template can accelarate the review process, thanks for your cooperation.
选择一个正确的`合并请求`模版可以加速审查流程，谢谢您的配合

If your `Pull Request` topic is not amoung the list above, please just delete all prepopulated template content.
如果您的`合并请求`内容不在上述的列表里，请删除提前填入的模版内容。

---

Thanks for your contribution to SecretFlow project
感谢您对于 SecretFlow 项目的贡献

2023-09-06 23:08 UTC, Zhangky11 commented
I have read the CLA Document and I hereby sign the CLA

2023-10-07 07:27 UTC, ligw1998 requested changes
Can you re-check the two ipynb files and make sure it works in your environment.

2023-10-07 07:27 UTC, ligw1998 commented on examples/security/v_lia/ExPLoitAttack/src/split_learning.ipynb
> +   ]
I encounter an error when running into this step:
INFO:root:SL Train Params: {'self': <ExP_attack.labelleakage.ExPloitattack.attach_ExPloitattack_to_splitnn_sf.<locals>.ExPloitAttackSplitNNWrapper_sf object at 0x7faa205b6640>, 'x': VDataFrame(partitions={PYURuntime(client): <secretflow.data.partition.pandas.partition.PdPartition object at 0x7faa206592e0>, PYURuntime(server): <secretflow.data.partition.pandas.partition.PdPartition object at 0x7faa2061d880>}, aligned=True), 'y': VDataFrame(partitions={PYURuntime(server): <secretflow.data.partition.pandas.partition.PdPartition object at 0x7faa2061de20>}, aligned=True), 'batch_size': 1024, 'epochs': 10, 'verbose': 1, 'callbacks': None, 'validation_data': (VDataFrame(partitions={PYURuntime(client): <secretflow.data.partition.pandas.partition.PdPartition object at 0x7faa2061d280>, PYURuntime(server): <secretflow.data.partition.pandas.partition.PdPartition object at 0x7faa2061d4f0>}, aligned=True), VDataFrame(partitions={PYURuntime(server): <secretflow.data.partition.pandas.partition.PdPartition object at 0x7fbc9b0d8460>}, aligned=True)), 'shuffle': False, 'sample_weight': None, 'validation_freq': 1, 'dp_spent_step_freq': None, 'dataset_builder': None, 'audit_log_params': {}, 'random_seed': 24065, 'save_path': './model/', 'audit_log_dir': None}

  0%|                                                                                                                                                                                                                                                 | 0/222 [00:00<?, ?it/s]

    ValueError: Layer "model" expects 2 input(s), but it received 1 input tensors. Inputs received: [<tf.Tensor 'hiddens:0' shape=(1024, 16) dtype=float32>]


It seems the server only receieve the embedding from one server(miss the one from the other).
I swtiched another server and the problem still exists. Can you have a look at this step and ensure if it works on your server/ personal environment?

2023-10-07 07:27 UTC, ligw1998 commented on examples/security/v_lia/NormAttack/split_learning.ipynb
Same question as the one in Exploit attack.

2023-10-07 21:34 UTC, Zhangky11 commented
I have read the CLA Document and I hereby sign the CLA

2023-10-07 21:54 UTC, Zhangky11 commented
I have fixed the bug and successfully ran the pipeline on my own machine.

2023-10-07 21:54 UTC, Zhangky11 commented on examples/security/v_lia/ExPLoitAttack/src/split_learning.ipynb
> +   ]
I have fixed the bug and successfully ran the pipeline on my own machine.

2023-10-07 21:54 UTC, Zhangky11 commented on examples/security/v_lia/NormAttack/split_learning.ipynb
I have fixed the bug and successfully ran the pipeline on my own machine.

2023-10-08 03:23 UTC, ligw1998 commented on examples/security/v_lia/ExPLoitAttack/src/split_learning.ipynb
> +   ]
The Norm Attack can be run successfully, however, the Exploit attack still can not be operated successfully.
The problem remains the same as mentioned above.

2023-10-08 03:35 UTC, ligw1998 commented on examples/security/v_lia/ExPLoitAttack/src/split_learning.ipynb
> +   ]
If you would like to see the errors in detail, i attach the ipynb file in Exploit attack here.
[split_learning.ipynb.zip](https://github.com/secretflow/secretflow/files/12839710/split_learning.ipynb.zip)

2023-10-08 03:36 UTC, Zhangky11 commented on examples/security/v_lia/ExPLoitAttack/src/split_learning.ipynb
> +   ]
It's weird. I am sure I could run the notebook successfully. Just to be on the safe side, I pushed the exploitAttack/src folder again.

2023-10-08 03:49 UTC, Zhangky11 commented on examples/security/v_lia/ExPLoitAttack/src/split_learning.ipynb
> +   ]
If it still cannot work, you could try adding this line here.
![b8c42873e8de8eef2320fb2959e2653](https://github.com/secretflow/secretflow/assets/79576162/41ceec66-65b0-4983-81f1-619b82df1f3d)

2023-10-08 04:30 UTC, ligw1998 commented on examples/security/v_lia/ExPLoitAttack/src/split_learning.ipynb
> +   ]
I'm afraid the problem lies in the [27] cell in the ipynb of Exploit attack. I substitute the fit_save func with the original fit function and the problem is solved. Since the fit/save func is orignally written in SLModel while fit_save func is implemented on your own, could you please go through the fit_save func (make sure everything is alright) or simply use fit func as the same in ipynb in norm attack.

2023-10-09 02:55 UTC, Zhangky11 commented on examples/security/v_lia/ExPLoitAttack/src/split_learning.ipynb
> +   ]
Sorry, this 'fit_save' function needs to save some intermediate variables and cannot directly use the existing API, so we need to implement it ourselves.

2023-10-09 02:59 UTC, ligw1998 commented on examples/security/v_lia/ExPLoitAttack/src/split_learning.ipynb
> +   ]
Have you re-checked the fit_save func, and ensure it is implemented correctly?

2023-10-09 03:03 UTC, Zhangky11 commented on examples/security/v_lia/ExPLoitAttack/src/split_learning.ipynb
> +   ]
To rule out any environment issues, I recreated a Conda environment, installed only the 'secretFlow' package, and then reran the program. It ran successfully without any errors. I'm not quite sure why you encountered this issue when running it.

2023-10-09 04:18 UTC, Zhangky11 commented on examples/security/v_lia/ExPLoitAttack/src/split_learning.ipynb
> +   ]
Could you try running the code on a different platform? Since I didn't encounter any errors on my platform, it's challenging to debug the issue.

2023-10-09 05:17 UTC, ligw1998 commented on examples/security/v_lia/ExPLoitAttack/src/split_learning.ipynb
> +   ]
Okay, im having a try.

2023-10-09 11:23 UTC, ligw1998 commented on examples/security/v_lia/ExPLoitAttack/src/split_learning.ipynb
> +   ]
It works on a local machine, seems to be the problem of remote server

2023-10-09 11:23 UTC, ligw1998 approved these changes

2023-10-09 11:23 UTC, ligw1998 approved these changes

2023-10-09 11:27 UTC, ligw1998 requested changes
Your code isn't manage to pass the Python Linter check. Can you use 'black' to reformat your python file?

2023-10-09 17:46 UTC, Zhangky11 commented
I have used black+isort to format all the python files. However, it seems that isort doesn't work directly with Jupyter notebook. I found some libraries online that claim to work with Jupyter notebook, but I'm not sure if they meet the requirements, so I haven't applied them to the notebook at the moment.

2023-10-10 02:35 UTC, ligw1998 commented
ExPLoitAttack/src/ExP_attack/labelleakage/__init__.py  NormAttack/attack/labelleakage/__init__.py NormAttack/utils/__init__.py
These three files need to be reformetted, check the message i sent you.

2023-10-10 04:34 UTC, Zhangky11 commented
I have reformatted all the files now.

2023-10-10 06:47 UTC, ligw1998 approved these changes
All requirements are met.

2023-10-10 06:48 UTC, merged